FROM docker.io/zmkfirmware/zmk-dev-arm:4.1-branch

ENV WORKSPACE_DIR=/workspaces/zmk

RUN git config --system --add safe.directory /workspaces/zmk \
    && git config --system --add safe.directory /workspaces/zmk-config